[package]
name = "kopki"
version = "0.1.2"
edition = "2021"

rust-version = "1.56"
authors = ["sugmaboy<jjmartinodev@outlook.com>"]
readme = "README.md"
license-file = "LICENSE"
description = "a simple graphical engine in wgpu and winit"
repository = "https://github.com/jjmartinodev/kopki"
keywords = ["graphics","gfx"]
categories = ["graphics", "rendering"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.14.3", features = ["derive"] }
pollster = "0.3.0"
wgpu = "0.19.1"
winit = "0.29.10"

[[test]]
name = "triangle"
path = "tests/triangle/main.rs"
harness = false

[[test]]
name = "clear"
path = "tests/clear/main.rs"
harness = false

[[test]]
name = "texture"
path = "tests/texture/main.rs"
harness = false

[[test]]
name = "uniform"
path = "tests/uniform/main.rs"
harness = false