[package]
name = "kopki"
version = "0.1.0"
edition = "2021"

rust-version = "1.56"
authors = ["sugmaboy<jjmartinodev@outlook.com>"]
readme = "README.md"
license-file = "LICENSE"
description = "a simple graphical engine in wgpu and winit"
repository = "https://github.com/jjmartinodev/anylist"
keywords = ["graphics","gfx"]
categories = ["graphics", "rendering"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.14.3", features = ["derive"] }
pollster = "0.3.0"
wgpu = "0.19.1"
winit = "0.29.10"

[[test]]
name = "triangle_test"
path = "triangle_test/main.rs"
harness = false

[[test]]
name = "clear_test"
path = "clear_test/main.rs"
harness = false

[[test]]
name = "texture_test"
path = "texture_test/main.rs"
harness = false